export const welcomImg=require("./welcomImg.png")
export const leftEllipse=require("./leftEllipse.png")
export const rightEllipse=require("./rightEllipse.png")
export const largeRightEllipse=require("./largeEllipse.png")
export const searchIcon=require("./searchIcon.png")

export const icBook=require("./icBook.png")
export const icSchool=require("./icSchool.png")
export const icShopping=require("./icShopping.png")
export const icWork=require("./icWork.png")
export const icWorkout=require("./icWorkout.png")
export const icDefault=require("./icDefault.png")
export const icPlus=require("./icPlus.png")