export const welcomImg=require("./welcomImg.png")
export const leftEllipse=require("./leftEllipse.png")
export const rightEllipse=require("./rightEllipse.png")
export const largeRightEllipse=require("./largeEllipse.png")
export const searchIcon=require("./searchIcon.png")